config/routes.rb
Rails.application.routes.draw do
  root 'characters#index'

  resources :characters, only: [:index, :create, :destroy] do
    member do
      post 'toggle_acted'
      post 'toggle_speed'
      post 'apply_damage'
      post 'apply_bonus_hp'
      post 'remove_bonus_hp'
    end

    collection do
      post 'reset_round'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates :hp, presence: true, numericality: { greater_than: 0 }
  validates :damage, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :bonus_hp, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_create :set_initial_damage

  scope :allies, -> { where(is_ally: true) }
  scope :enemies, -> { where(is_ally: false) }
  scope :fast, -> { where(fast_turn: true) }
  scope :slow, -> { where(fast_turn: false) }

  def self.ordered_for_initiative
    [
      fast.allies.order(:id),
      fast.enemies.order(:id),
      slow.allies.order(:id),
      slow.enemies.order(:id)
    ].flatten
  end

  def initiative_group
    group = fast_turn? ? "Fast" : "Slow"
    type = is_ally? ? "Ally" : "Enemy"
    "#{group} #{type}"
  end

  def total_hp
    hp + bonus_hp
  end

  def apply_damage(amount)
    return if amount.nil? || amount <= 0

    # First reduce bonus HP
    if bonus_hp > 0
      if amount <= bonus_hp
        self.bonus_hp -= amount
        amount = 0
      else
        amount -= bonus_hp
        self.bonus_hp = 0
      end
    end

    # Then add to damage if there's still damage to apply
    if amount > 0
      self.damage += amount
    end

    save
  end

  def apply_bonus_hp(amount)
    return if amount.nil?

    if amount.negative?
      subtract_bonus_hp(-amount)
    else
      self.bonus_hp += amount
    end

    save
  end

  def remove_bonus_hp
    self.bonus_hp = 0
    save
  end

  def heal_damage(amount)
    return if amount.nil? || amount <= 0

    # reduce damage first
    if amount <= damage
      self.damage -= amount
    else
      # if extra healing, restore bonus HP
      self.bonus_hp += (amount - damage)
      self.damage = 0
    end

    save
  end

  private

  def set_initial_damage
    self.damage ||= 0
    self.bonus_hp ||= 0
  end

  def subtract_bonus_hp(amount)
    self.bonus_hp -= [amount, bonus_hp].min # ensure bonus HP does not go below 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.ordered_for_initiative
    @new_character = Character.new
  end

  def create
    @character = Character.new(character_params)

    puts "Character params: #{character_params.inspect}"

    if @character.save
      redirect_to root_path, notice: 'Character added!'
    else
      puts "Character errors: #{@character.errors.full_messages}"
      @characters = Character.ordered_for_initiative
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to root_path, notice: 'Character removed!'
  end

  def toggle_acted
    @character = Character.find(params[:id])
    @character.update(acted: !@character.acted)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  def toggle_speed
    @character = Character.find(params[:id])
    @character.update(fast_turn: !@character.fast_turn)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  def apply_damage
    @character = Character.find(params[:id])
    damage_amount = params[:damage_amount].to_i

    if damage_amount.negative?
      @character.heal_damage(-damage_amount)
    else
      @character.apply_damage(damage_amount)
    end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end


  def apply_bonus_hp
    @character = Character.find(params[:id])
    bonus_hp_amount = params[:bonus_hp_amount].to_i
    @character.apply_bonus_hp(bonus_hp_amount)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end


  def remove_bonus_hp
    @character = Character.find(params[:id])
    @character.remove_bonus_hp

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  def reset_round
    Character.update_all(acted: false)
    redirect_to root_path, notice: 'New round started!'
  end

  private

  def character_params
    params.require(:character).permit(:name, :hp, :is_ally, :fast_turn)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def health_status_class(character)
    return '' if character.hp.nil?

    damage = character.damage || 0
    total_hp = character.total_hp

    # Add these lines to help debug
    Rails.logger.debug "Character: #{character.name}"
    Rails.logger.debug "Total HP: #{total_hp}"
    Rails.logger.debug "Damage: #{damage}"
    Rails.logger.debug "Injured threshold: #{total_hp / 2}"

    return '' if damage == 0
    return 'incapacitated' if damage >= total_hp
    return 'injured' if damage >= (total_hp / 2)
    ''
  end
end

app/views/characters/_character.html.erb
<%= turbo_frame_tag dom_id(character) do %>
  <div class="character-card <%= 'acted' if character.acted %> <%= health_status_class(character) %>">
    <span class="name"><%= character.name %></span>
    <div class="stats">
      <div class="hp-container">
        <div class="hp-section">
          <span class="damage-display">
            <% if character.hp %>
              <%= character.damage %>/<%= character.total_hp %>
              (<%= character.hp %> + <%= character.bonus_hp %> Bonus)
            <% else %>
              N/A
            <% end %>
          </span>
        </div>
        <div class="hp-controls">
          <form action="<%= apply_damage_character_path(character) %>" method="post" data-turbo="true">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <input type="number" name="damage_amount" placeholder="Damage" class="damage-input" min="-1000">
            <input type="submit" value="Apply" class="damage-button">
          </form>
          <%= form_with(url: apply_bonus_hp_character_path(character), method: :post, data: { turbo: true }) do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= f.number_field :bonus_hp_amount,
                name: 'bonus_hp_amount',
                placeholder: "Bonus (+/-)",
                class: 'bonus-hp-input',
                step: 1 %>
            <%= f.submit "Apply", class: 'bonus-hp-button' %>
          <% end %>
          <% if character.bonus_hp > 0 %>
            <form action="<%= remove_bonus_hp_character_path(character) %>" method="post" data-turbo="true">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <input type="submit" value="Remove Bonus HP" class="remove-bonus-hp-button">
            </form>
          <% end %>
        </div>
      </div>
    </div>
    <div class="actions">
      <form action="<%= toggle_acted_character_path(character) %>" method="post" data-turbo="true">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="submit" value="<%= character.acted? ? 'Undo Action' : 'Mark Action Complete' %>" class="action-button">
      </form>
      <form action="<%= toggle_speed_character_path(character) %>" method="post" data-turbo="true">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="submit" value="<%= character.fast_turn? ? 'Switch to Slow' : 'Switch to Fast' %>" class="speed-button">
      </form>
      <%= button_to character_path(character), method: :delete, class: "remove-button", data: { turbo_confirm: "Remove #{character.name}?" } do %>
        Remove
      <% end %>
    </div>
  </div>
<% end %>

app/views/characters/apply_bonus_hp.turbo_stream.erb
<%= turbo_stream.replace dom_id(@character) do %>
  <%= render partial: "character", locals: { character: @character } %>
<% end %>

app/views/characters/index.html.erb
<div class="container">
  <h1>Shadow of the Demon Lord Initiative Tracker</h1>
  <div class="character-form">
    <h2>Add New Character</h2>
    <%= form_with(model: @new_character, local: true) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="field">
        <%= f.label :hp, "Health" %>
        <%= f.number_field :hp, required: true, min: 1 %>
      </div>
      <div class="field">
        <%= f.label :is_ally, "Character Type" %>
        <%= f.select :is_ally, [['Ally', true], ['Enemy', false]] %>
      </div>
      <div class="field">
        <%= f.label :fast_turn, "Turn Speed" %>
        <%= f.select :fast_turn, [['Fast', true], ['Slow', false]] %>
      </div>
      <%= f.submit "Add Character", class: "button" %>
    <% end %>
  </div>
  <div class="initiative-tracker">
    <h2>Current Initiative Order</h2>
    <%= button_to "Reset Round", reset_round_characters_path,
        class: "reset-button",
        data: { turbo_confirm: "Start new round?" } %>
    <div class="characters-list">
      <% @characters.group_by(&:initiative_group).each do |group, characters| %>
        <div class="initiative-group">
          <h3><%= group %></h3>
          <% characters.each do |character| %>
            <%= turbo_frame_tag dom_id(character) do %>
              <%= render partial: "character", locals: { character: character } %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/remove_bonus_hp.turbo_stream.erb
<%= turbo_stream.replace dom_id(@character) do %>
  <%= render partial: "character", locals: { character: @character } %>
<% end %>

app/views/characters/toggle_acted.turbo_stream.erb
<%= turbo_stream.replace dom_id(@character) do %>
  <%= render partial: "character", locals: { character: @character } %>
<% end %>

app/views/characters/toggle_speed.turbo_stream.erb
<%= turbo_stream.replace dom_id(@character) do %>
  <%= render partial: "character", locals: { character: @character } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SotDL Initiative Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>